logging:
  level:
    org:
      springframework:
        security: DEBUG

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    schema: classpath:/script/schema.sql
    data: classpath:/script/data.sql

oauth2-config:
  jksConfigFileName: security/jwt.jks
  keyPassword: changeit
  jksKeyAlias: lms-dev-keystore
  userScopes: true
  accessTokenValiditySeconds: 10
  refreshTokenValiditySeconds: 10